apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: neo4j-escodb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: neo4j-escodb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: neo4j-escodb
        image: dfcdevsharedcr.azurecr.io/ncs.servicetaxonomy.escodb:__DFCServiceTaxonomyDatabaseTag__
        env:
        - name: NEO4J_PWD
          valueFrom:
            secretKeyRef: 
              name: neo4j-account-secret
              key: password
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef: 
              name: neo4j-account-secret
              key: auth
        - name: NEO4J_dbms_connectors_default__advertised__address
          value: __Neo4jCustomHostname__
        ports:
        - containerPort: 7474
        - containerPort: 7473
        - containerPort: 7687
        resources:
          requests:
            cpu: 1500m
            memory: "16G"
          limits:
            cpu: 1500m
            memory: "16G"
        volumeMounts:
        - name: certificates
          mountPath: /var/certificates
        - name: esco-rdf-files
          mountPath: /var/lib/neo4j/import
      volumes:
      - name: certificates
        azureFile:
          secretName: staxsharedstr-account-secret
          shareName: certificates
          readOnly: true
      - name: esco-rdf-files
        azureFile:
          secretName: staxsharedstr-account-secret
          shareName: esco-rdf-files
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      service.beta.kubernetes.io/neo4j-escodb-resource-group: __StaxDbPublicIpAddressResourceGroup__
  name: neo4j-escodb
spec:
  type: LoadBalancer
  loadBalancerIP: __StaxDbPublicIpAddress__
  ports:
  - name: http 
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: https
    protocol: TCP
    port: 7473
    targetPort: 7473
  - name: query 
    protocol: TCP
    port: 7687
    targetPort: 7687
  selector:
    app: neo4j-escodb