variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
  SolutionBaseName: DFC.ServiceTaxonomy.Database

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.7.3
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:

- stage: Build
  variables:
    #TO DO: decide how to tag and publish image builds from branches
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    - name: AppImageName
      value: NCS.ServiceTaxonomy.EscoDb:$(Build.BuildNumber)
  jobs:
  - template: JobTemplates/Build.yml
    parameters:
      AppImageName: $(AppImageName)
      ArmTemplateRoot: ${{ variables.ArmTemplateRoot }}
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)
      SolutionBaseName: ${{ variables.SolutionBaseName }}

- stage: DeployToDev
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    - group: dfc-stax-shared-dev
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AzureResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      KubernetesCluster: $(sharedAksCluster)
      ParentBusinessTag: $(ParentBusiness)
      ServiceOfferingTag: $(ServiceOffering)
      StaxSharedStorageAccountKey: $(dfcdevstaxsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)


