variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
  SolutionBaseName: DFC.ServiceTaxonomy.Database

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.7.3
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:

- stage: Build
  variables:
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    #TO DO: decide how to tag and publish image builds from branches
    - name: AppImageName
      value: NCS.ServiceTaxonomy.EscoDb:$(Build.BuildNumber)
  jobs:
  - template: JobTemplates/BuildResources.yml
    parameters:
      ArmTemplateRoot: ${{ variables.ArmTemplateRoot }}
      SolutionBaseName: ${{ variables.SolutionBaseName }}
  - template: JobTemplates/BuildContainer.yml
    parameters:
      AppImageName: $(AppImageName)
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)
  - job: PublishArtifacts
    pool: 'NCS - CI and CD'
    steps:
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact: LoadTest'
      inputs:
        targetPath: 'Tests/LoadTests'
        artifactName: LoadTests

- stage: DeployToDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    - group: dfc-stax-shared-dev
    - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      KubernetesCluster: $(sharedAksCluster)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      StaxSharedStorageAccountKey: $(dfcdevstaxsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
  - template: JobTemplates/Test.yml
    parameters:
      Environment: DEV_SERVICETAXONOMY
      # The path to the bin directory of jMeter on the agent that will be running the test
      JMeterBinDir: /opt/apache-jmeter-5.2.1/bin
      # The hostname of the server the test will be ran against
      ServerName: dfc-$ReleaseEnvironmentName-stax-database.cloudapp.azure.com


