variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
  ImageBaseName: NCS.ServiceTaxonomy.EscoDb
  Image1BaseName: NCS.ServiceTaxonomy.EscoDb-1
  DraftImageBaseName: NCS.ServiceTaxonomy.DraftEscoDB
  Draft1ImageBaseName: NCS.ServiceTaxonomy.DraftEscoDB-1
  VisitImageBaseName: NCS.ServiceTaxonomy.VisitDb
  Visit1ImageBaseName: NCS.ServiceTaxonomy.VisitDb-1
  SolutionBaseName: DFC.ServiceTaxonomy.Database

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'
  - repository: dfc-servicetaxonomy-editor
    type: github
    name: SkillsFundingAgency/dfc-servicetaxonomy-editor
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:

- stage: Build
  variables:
    - group: dfc-shared-all
    - group: dfc-shared-dev

  jobs:
  - template: JobTemplates/BuildResources.yml
    parameters:
      ArmTemplateRoot: ${{ variables.ArmTemplateRoot }}
      SolutionBaseName: ${{ variables.SolutionBaseName }}
  - template: JobTemplates/BuildContainer.yml
    parameters:
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      DevSitContainerRegistryAdminUser: $(DevContainerRegistryAdminUser)
      DevSitContainerRegistryPassword: $(DevContainerRegistryPassword)
      PrdContainerRegistryAdminUser: $(PrdContainerRegistryAdminUser)
      PrdContainerRegistryPassword: $(PrdContainerRegistryPassword)
      DockerfileContext: 'Resources/Dockerfiles'
      DockerfileName: 'neo4jescodb.Dockerfile'
      DraftDockerfileName: 'neo4jDraftescodb.Dockerfile'
      VisitDockerfileName: 'neo4jVisit.Dockerfile'
      ImageBaseName: ${{ variables.ImageBaseName }}
      Image1BaseName: ${{ variables.Image1BaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      Draft1ImageBaseName: ${{ variables.Draft1ImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      Visit1ImageBaseName: ${{ variables.Visit1ImageBaseName }}
      #TO DO: decide how to tag and publish image builds from branches
      ImageTag: $(Build.BuildNumber)

- stage: DeployToDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    - group: dfc-stax-shared-dev
    - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      Environment: DEV_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcdevstaxsharedstr)
      StaxDraftStorageAccountKey: $(dfcdevstaxdraftsharedstr)
      StaxVisitStorageAccountKey: $(dfcdevstaxvisitsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

- stage: DeployToSit
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-sit-shared-kv
    - group: dfc-shared-sit
    - group: dfc-stax-shared-sit
    - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      Environment: SIT_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcsitstaxsharedstr)
      StaxDraftStorageAccountKey: $(dfcsitstaxdraftsharedstr)
      StaxVisitStorageAccountKey: $(dfcsitstaxvisitsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

- stage: DeployToPP
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-pp-shared-kv
    - group: dfc-shared-pp
    - group: dfc-stax-shared-pp
    - template: VariableTemplates\PPEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy-pp.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      CertificateSecretName1: $(DatabaseCertificateSecretName1)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName1: $(DraftDatabaseCertificateSecretName1)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName1: $(VisitDatabaseCertificateSecretName1)
      Environment: PP_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      Image1BaseName: ${{ variables.Image1BaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      Draft1ImageBaseName: ${{ variables.Draft1ImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      Visit1ImageBaseName: ${{ variables.Visit1ImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcppstaxsharedstr)
      StaxSharedStorageAccount1Key: $(dfcppstaxsharedstr1)
      StaxDraftStorageAccountKey: $(dfcppstaxdraftsharedstr)
      StaxDraftStorageAccount1Key: $(dfcppstaxdraftsharedstr1)
      StaxVisitStorageAccountKey: $(dfcppstaxvisitsharedstr)
      StaxVisitStorageAccount1Key: $(dfcppstaxvisitsharedstr1)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxSharedStorageAccountName1: $(StaxSharedStorageAccountName1)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxDraftStorageAccountName1: $(StaxDraftStorageAccountName1)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxVisitStorageAccountName1: $(StaxVisitStorageAccountName1)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

- stage: DeployToPRD
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-prd-shared-kv
    - group: dfc-shared-prd
    - group: dfc-stax-shared-prd
    - template: VariableTemplates\PrdEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy-prd.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      CertificateSecretName1: $(DatabaseCertificateSecretName1)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName1: $(DraftDatabaseCertificateSecretName1)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName1: $(VisitDatabaseCertificateSecretName1)
      Environment: PRD_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      Image1BaseName: ${{ variables.Image1BaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      Draft1ImageBaseName: ${{ variables.Draft1ImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      Visit1ImageBaseName: ${{ variables.Visit1ImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcprdstaxsharedstr)
      StaxSharedStorageAccount1Key: $(dfcprdstaxsharedstr1)
      StaxDraftStorageAccountKey: $(dfcprdstaxdraftsharedstr)
      StaxDraftStorageAccount1Key: $(dfcprdstaxdraftsharedst1)
      StaxVisitStorageAccountKey: $(dfcprdstaxvisitsharedstr)
      StaxVisitStorageAccount1Key: $(dfcprdstaxvisitsharedst1)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxSharedStorageAccountName1: $(StaxSharedStorageAccountName1)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxDraftStorageAccountName1: $(StaxDraftStorageAccountName1)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxVisitStorageAccountName1: $(StaxVisitStorageAccountName1)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

