variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
  ImageBaseName: NCS.ServiceTaxonomy.EscoDb
  DraftImageBaseName: NCS.ServiceTaxonomy.DraftEscoDB
  VisitImageBaseName: NCS.ServiceTaxonomy.VisitDb
  SolutionBaseName: DFC.ServiceTaxonomy.Database

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.0
    endpoint: 'GitHub (ESFA)'
  - repository: dfc-servicetaxonomy-editor
    type: github
    name: SkillsFundingAgency/dfc-servicetaxonomy-editor
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:

- stage: Refresh
  variables:
    - group: dfc-shared-all
    - group: dfc-shared-dev
    - group: 'KeyVault - dfc-dev-shared-kv'
  jobs:
  - template: JobTemplates/RefreshEnvironment.yml
    parameters:
      ArmTemplateRoot: ${{ variables.ArmTemplateRoot }}
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      DBPassword: $(dfc-dev-shared-sql)

- stage: Build
  variables:
    - group: dfc-shared-all
    - group: dfc-shared-dev
    
  jobs:
  - template: JobTemplates/BuildResources.yml
    parameters:
      ArmTemplateRoot: ${{ variables.ArmTemplateRoot }}
      SolutionBaseName: ${{ variables.SolutionBaseName }}
  - template: JobTemplates/BuildContainer.yml
    parameters:
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      DevSitContainerRegistryAdminUser: $(DevContainerRegistryAdminUser)
      DevSitContainerRegistryPassword: $(DevContainerRegistryPassword)
      PrdContainerRegistryAdminUser: $(PrdContainerRegistryAdminUser)
      PrdContainerRegistryPassword: $(PrdContainerRegistryPassword)
      DockerfileContext: 'Resources/Dockerfiles'
      DockerfileName: 'neo4jescodb.Dockerfile'
      DraftDockerfileName: 'neo4jDraftescodb.Dockerfile'
      VisitDockerfileName: 'neo4jVisit.Dockerfile'
      ImageBaseName: ${{ variables.ImageBaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      #TO DO: decide how to tag and publish image builds from branches
      ImageTag: $(Build.BuildNumber)

- stage: DeployToDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-dev-shared-kv
    - group: dfc-shared-dev
    - group: dfc-stax-shared-dev
    - template: VariableTemplates\DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      Environment: DEV_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcdevstaxsharedstr)
      StaxDraftStorageAccountKey: $(dfcdevstaxdraftsharedstr)
      StaxVisitStorageAccountKey: $(dfcdevstaxvisitsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

- stage: DeployToSit
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-sit-shared-kv
    - group: dfc-shared-sit
    - group: dfc-stax-shared-sit
    - template: VariableTemplates\SitEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      DraftDatabaseCertificateSecretName: $(DraftDatabaseCertificateSecretName)
      VisitDatabaseCertificateSecretName: $(VisitDatabaseCertificateSecretName)
      Environment: SIT_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      DraftImageBaseName: ${{ variables.DraftImageBaseName }}
      VisitImageBaseName: ${{ variables.VisitImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcsitstaxsharedstr)
      StaxDraftStorageAccountKey: $(dfcsitstaxdraftsharedstr)
      StaxVisitStorageAccountKey: $(dfcsitstaxvisitsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxDraftStorageAccountName: $(StaxDraftStorageAccountName)
      StaxVisitStorageAccountName: $(StaxVisitStorageAccountName)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)

- stage: DeployToPP
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    - group: dfc-shared-all
    - group: dfc-stax-shared-all
    - group: KeyVault - dfc-pp-shared-kv
    - group: dfc-shared-pp
    - group: dfc-stax-shared-pp
    - template: VariableTemplates\PPEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      CertificateSecretName: $(DatabaseCertificateSecretName)
      Environment: PP_SERVICETAXONOMY
      EnvironmentTag: $(EnvironmentTag)
      ImageBaseName: ${{ variables.ImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      Neo4jPassword: $(Neo4jPassword)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(ResourceGroup)
      ServiceOfferingTag: $(ServiceOffering)
      SolutionBaseName: ${{ variables.SolutionBaseName }}
      StaxSharedStorageAccountKey: $(dfcppstaxsharedstr)
      StaxSharedStorageAccountName: $(StaxSharedStorageAccountName)
      StaxSharedStorageAccountResourceGroup: $(StaxSharedResourceGroup)


