parameters:
  ContainerRegistryAdminUser: ''
  ContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  ImageBaseName: ''
  ImageTag: ''
  SolutionBaseName: ''

jobs:
- job: BuildNCSServiceTaxonomyEscoDbContainer
  displayName: Build and publish NCS.ServiceTaxonomy.EscoDb container
  pool: 'Hosted Ubuntu 1604'
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish.yml
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.ContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.ContainerRegistryPassword }}
      DockerfileContext: ${{ parameters.DockerfileContext }}
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
  - task: CopyFiles@2
    displayName: 'Copy Manifest File to: $(Build.ArtifactStagingDirectory)\Manifest'
    inputs:
      Contents: 'Resources/Dockerfiles/neo4jescodb.yaml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\Manifest'
      flattenFolders: true
  - task: PublishPipelineArtifact@0
    displayName: Publish Pipeline Artifact
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)\Manifest
      artifactName: ${{ parameters.SolutionBaseName }}.Manifest