parameters:
  DevSitContainerRegistryAdminUser: ''
  DevSitContainerRegistryPassword: ''
  PrdContainerRegistryAdminUser: ''
  PrdContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  DraftDockerfileName: ''
  VisitDockerfileName: ''
  ImageBaseName: ''
  Image1BaseName: ''
  DraftImageBaseName: ''
  Draft1ImageBaseName: ''
  VisitImageBaseName: ''
  Visit1ImageBaseName: ''
  ImageTag: ''

jobs:
- job: BuildNCSServiceTaxonomyEscoDbContainer
  displayName: Build and publish NCS.ServiceTaxonomy.EscoDb container
  pool: 'NCS - Docker'
  steps:
  - checkout: self
  - checkout: dfc-servicetaxonomy-editor
  - template: ../StepTemplates/CreateJarFile.yml
    parameters:
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DraftDockerfileName }}
      ImageBaseName: ${{ parameters.DraftImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jDraftescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.VisitDockerfileName }}
      ImageBaseName: ${{ parameters.VisitImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jVisit.yaml'
# Below Images are for Pre-Prod and Prod Env's, This needs refactoring
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.Image1BaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jescodb-1.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DraftDockerfileName }}
      ImageBaseName: ${{ parameters.DraftImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jDraftescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DraftDockerfileName }}
      ImageBaseName: ${{ parameters.Draft1ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jDraftescodb-1.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.VisitDockerfileName }}
      ImageBaseName: ${{ parameters.VisitImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jVisit.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.VisitDockerfileName }}
      ImageBaseName: ${{ parameters.Visit1ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jVisit-1.yaml'
 
        