parameters:
  SolutionBaseName: ''
  DevSitContainerRegistryAdminUser: ''
  DevSitContainerRegistryPassword: ''
  PrdContainerRegistryAdminUser: ''
  PrdContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  ImageBaseName: ''
  ImageTag: ''

jobs:
- job: BuildNCSServiceTaxonomyEscoDbContainer
  displayName: Build and publish NCS.ServiceTaxonomy.EscoDb container
  pool: 'Hosted Ubuntu 1604'
  steps:
  - checkout: self
  - checkout: dfc-servicetaxonomy-editor
  - script: dir $(Build.SourcesDirectory)
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: '$(Build.SourcesDirectory)/${{ parameters.SolutionBaseName }}/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: '$(Build.SourcesDirectory)/${{ parameters.SolutionBaseName }}/Resources/Dockerfiles/neo4jescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: '$(Build.SourcesDirectory)/${{ parameters.SolutionBaseName }}/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}