parameters:
  ContainerRegistryAdminUser: ''
  ContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  ImageBaseName: ''
  ImageTag: ''
  SolutionBaseName: ''

jobs:
- job: BuildNCSServiceTaxonomyEscoDbContainer
  displayName: Build and publish NCS.ServiceTaxonomy.EscoDb container
  pool: 'Hosted Ubuntu 1604'
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.ContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.ContainerRegistryPassword }}
      DockerfileContext: ${{ parameters.DockerfileContext }}
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: Resources/Dockerfiles/neo4jescodb.yaml