parameters:
  DevSitContainerRegistryAdminUser: ''
  DevSitContainerRegistryPassword: ''
  PrdContainerRegistryAdminUser: ''
  PrdContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  ImageBaseName: ''
  ImageTag: ''

jobs:
- job: BuildNCSServiceTaxonomyEscoDbContainer
  displayName: Build and publish NCS.ServiceTaxonomy.EscoDb container
  pool: 'Hosted Ubuntu 1604'
  steps:
  - checkout: self
  - checkout: dfc-servicetaxonomy-editor
  - script: dir $(Build.SourcesDirectory)
  - task: DeleteFiles@1
    displayName: 'Remove unneeded jar files'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/dfc-servicetaxonomy-editor/DFC.ServiceTaxonomy.Neo4j/Java Plugins/target'
      contents: |
        *.jar
  - template: ../StepTemplates/dfc-maven-build.yml
    parameters:
      mavenPomFile: 'dfc-servicetaxonomy-editor/DFC.ServiceTaxonomy.Neo4j/Java Plugins/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
  - task: DeleteFiles@1
    displayName: 'Remove unneeded jar files from the maven build'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/dfc-servicetaxonomy-editor/DFC.ServiceTaxonomy.Neo4j/Java Plugins/target'
      contents: |
        original*.jar
  - script: |
      dir '$(Build.SourcesDirectory)/dfc-servicetaxonomy-editor/DFC.ServiceTaxonomy.Neo4j/Java Plugins/target'
      dir '$(Build.SourcesDirectory)/dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      mkdir '$(Build.SourcesDirectory)/dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}/plugins'
      dir '$(Build.SourcesDirectory)/dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
    displayName: 'md plugins folder under Dockerfiles'
  - task: CopyFiles@2
    displayName: 'Copy jar files to Dockerfiles'
    inputs:
      contents: |
        'dfc-servicetaxonomy-editor/DFC.ServiceTaxonomy.Neo4j/Java Plugins/target/*.jar'
      targetFolder: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}/plugins'
      flattenFolders: true
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'dfc-servicetaxonomy-database/Resources/Dockerfiles/neo4jescodb.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: 'dfc-servicetaxonomy-database/${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}


        