parameters:
  ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.ServiceTaxonomy.Database.Resources.ArmTemplates'
  AksResourceGroup: ''
  AzureSubscriptionEndpoint: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
  CertificateSecretName: ''
  CertificateSecretName1: ''
  DraftDatabaseCertificateSecretName: ''
  DraftDatabaseCertificateSecretName1: ''
  VisitDatabaseCertificateSecretName: ''
  VisitDatabaseCertificateSecretName1: ''
  Environment: ''
  EnvironmentTag: ''
  ImageBaseName: ''
  Image1BaseName: ''
  DraftImageBaseName: ''
  Draft1ImageBaseName: ''
  VisitImageBaseName: ''
  Visit1ImageBaseName: ''
  KeyVaultName: ''
  KubernetesCluster: ''
  Neo4jPassword: ''
  ParentBusinessTag: ''
  ResourceGroup: ''
  ServiceOfferingTag: ''
  SolutionBaseName: ''
  StaxSharedStorageAccountKey: ''
  StaxSharedStorageAccount1Key: ''
  StaxDraftStorageAccountKey: ''
  StaxDraftStorageAccount1Key: ''
  StaxVisitStorageAccountKey: ''
  StaxVisitStorageAccount1Key: ''
  StaxSharedStorageAccountName: ''
  StaxSharedStorageAccountName1: ''
  StaxDraftStorageAccountName: ''
  StaxDraftStorageAccountName1: ''
  StaxVisitStorageAccountName: ''
  StaxVisitStorageAccountName1: ''
  StaxSharedStorageAccountResourceGroup: ''

jobs:
- deployment: DeployARMTemplatesTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
          parameters:
            ArmTemplateRoot: ${{ parameters.ArmTemplateRoot }}
            AzureSubscription: ${{ parameters.AzureSubscriptionEndpoint }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ParentBusinessTag: ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}

- deployment: DeployPrimaryNeo4JEscoDBTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  displayName: "Deploy Primary Neo4jEscoDB"
  environment: ${{ parameters.Environment }}
  dependsOn:
  - DeployARMTemplatesTo_${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.CertificateSecretName }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.ImageBaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxSharedStorageAccountKey }}
            StaxSharedStorageAccountName: ${{ parameters.StaxSharedStorageAccountName }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }}  
            SecretName: staxsharedstr-account-secret
            ManifestFileName: neo4jescodb.yaml

- deployment: DeploySecondaryNeo4JEscoDBTo_${{ parameters.Environment }} 
  displayName: "Deploy Secondary Neo4jEscoDB" 
  environment: ${{ parameters.Environment }} 
  dependsOn: 
  - DeployPrimaryNeo4JEscoDBTo_${{ parameters.Environment }} 
  strategy: 
    runOnce: 
      deploy: 
        steps:
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.CertificateSecretName1 }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.Image1BaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxSharedStorageAccount1Key }}
            StaxSharedStorageAccountName: ${{ parameters.StaxSharedStorageAccountName1 }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }}  
            SecretName: staxsharedstr1-account-secret
            ManifestFileName: neo4jescodb-1.yaml 

- deployment: DeployPrimaryNeo4JEscoDBDraftTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  displayName: "Deploy Primary Neo4jEscoDB Draft" 
  environment: ${{ parameters.Environment }} 
  dependsOn: 
  - DeploySecondaryNeo4JEscoDBTo_${{ parameters.Environment }} 
  strategy: 
    runOnce: 
      deploy: 
        steps: 
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.DraftDatabaseCertificateSecretName }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.DraftImageBaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxDraftStorageAccountKey }}
            StaxSharedStorageAccountName: ${{ parameters.StaxDraftStorageAccountName }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }} 
            SecretName: staxdraftsharedstr-account-secret 
            ManifestFileName: neo4jDraftescodb.yaml        

- deployment: DeploySecondaryNeo4JEscoDBDraftTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  displayName: "Deploy Secondary Neo4jEscoDB Draft" 
  environment: ${{ parameters.Environment }} 
  dependsOn: 
  - DeployPrimaryNeo4JEscoDBDraftTo_${{ parameters.Environment }} 
  strategy: 
    runOnce: 
      deploy: 
        steps: 
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.DraftDatabaseCertificateSecretName1 }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.Draft1ImageBaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxDraftStorageAccount1Key }}
            StaxSharedStorageAccountName: ${{ parameters.StaxDraftStorageAccountName1 }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }} 
            SecretName: staxdraftsharedstr1-account-secret 
            ManifestFileName: neo4jDraftescodb-1.yaml
 
- deployment: DeployPrimaryNeo4JVisitsTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD' 
  displayName: "Deploy Primary Neo4jVisits" 
  environment: ${{ parameters.Environment }} 
  dependsOn: 
  - DeploySecondaryNeo4JEscoDBDraftTo_${{ parameters.Environment }} 
  strategy: 
    runOnce: 
      deploy: 
        steps:
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.VisitDatabaseCertificateSecretName }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.VisitImageBaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxVisitStorageAccountKey }}
            StaxSharedStorageAccountName: ${{ parameters.StaxVisitStorageAccountName }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }}  
            SecretName: staxvisitsharedstr-account-secret
            ManifestFileName: neo4jVisit.yaml 

- deployment: DeploySecondaryNeo4JVisitsTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD' 
  displayName: "Deploy Secondary Neo4jVisits" 
  environment: ${{ parameters.Environment }} 
  dependsOn: 
  - DeployPrimaryNeo4JVisitsTo_${{ parameters.Environment }} 
  strategy: 
    runOnce: 
      deploy: 
        steps: 
        - template: ../StepTemplates/DeployNeo4j.yml
          parameters:
            AksResourceGroup: ${{ parameters.AksResourceGroup }}
            AzureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint}}
            CertificateSecretName: ${{ parameters.VisitDatabaseCertificateSecretName1 }}
            Environment: ${{ parameters.Environment }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ImageBaseName: ${{ parameters.Visit1ImageBaseName }}
            KeyVaultName: ${{ parameters.KeyVaultName }}
            KubernetesCluster: ${{ parameters.KubernetesCluster }}
            Neo4jPassword: ${{ parameters.Neo4jPassword }}
            ParentBusinessTag:  ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
            SolutionBaseName: ${{ parameters.SolutionBaseName }}
            StaxSharedStorageAccountKey: ${{ parameters.StaxVisitStorageAccount1Key }}
            StaxSharedStorageAccountName: ${{ parameters.StaxVisitStorageAccountName1 }}
            StaxSharedStorageAccountResourceGroup: ${{ parameters.StaxSharedStorageAccountResourceGroup }}  
            SecretName: staxvisitsharedstr1-account-secret 
            ManifestFileName: neo4jVisit-1.yaml
            