parameters:
  ArmTemplateRoot: ''
  SolutionBaseName: ''

jobs:
- job: TestAndPublishArmTemplates
  displayName: Test and Publish Arm Templates
  pool: 'NCS - CI and CD'
  steps:
  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureConnectionType: 'connectedServiceName' # Optional. Options: connectedServiceName, connectedServiceNameARM
      azureClassicSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)' # Required when azureConnectionType == ConnectedServiceName
      #azureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)' # Required when azureConnectionType == ConnectedServiceNameARM
      authenticationType: 'server' # Options: server, aadAuthenticationPassword, aadAuthenticationIntegrated, connectionString
      serverName: 'dfc-dev-shared-sql.database.windows.net' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated
      databaseName: 'dfc-dev-stax-editor-db' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated
      sqlUsername: 'dfc_sqladmin' # Required when authenticationType == Server
      sqlPassword: '$(dfc-dev-shared-sql)' # Required when authenticationType == Server
      #aadSqlUsername: # Required when authenticationType == AadAuthenticationPassword
      #aadSqlPassword: # Required when authenticationType == AadAuthenticationPassword
      #connectionString: # Required when authenticationType == ConnectionString
      deployType: 'inlineSqlTask' # Options: dacpacTask, sqlTask, inlineSqlTask
      #deploymentAction: 'Publish' # Required when deployType == DacpacTask. Options: publish, extract, export, import, script, driftReport, deployReport
      #dacpacFile: # Required when deploymentAction == Publish || DeploymentAction == Script || DeploymentAction == DeployReport
      #bacpacFile: # Required when deploymentAction == Import
      #sqlFile: # Required when deployType == SqlTask
      sqlInline: 'SELECT [Id],[DocumentId],[Alias],[ContentItemId],[Latest],[Published] FROM [dbo].[AliasPartIndex]' # Required when deployType == InlineSqlTask
      #publishProfile: # Optional
      #additionalArguments: # Optional
      #sqlAdditionalArguments: # Optional
      #inlineAdditionalArguments: # Optional
      ipDetectionMethod: 'AutoDetect' # Options: autoDetect, iPAddressRange
      #startIpAddress: # Required when ipDetectionMethod == IPAddressRange
      #endIpAddress: # Required when ipDetectionMethod == IPAddressRange
      #deleteFirewallRule: true # Optional
