parameters:
  DBPassword: ''

jobs:
- job: TestAndPublishArmTemplates
  displayName: Test and Publish Arm Templates
  pool: 'NCS - CI and CD'
  steps:
  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureConnectionType: 'ConnectedServiceNameARM' # Optional. Options: connectedServiceName, connectedServiceNameARM
      azureSubscription: '$(AzureDevOpsServiceConnection)' # Required when azureConnectionType == ConnectedServiceNameARM
      authenticationType: 'server' # Options: server, aadAuthenticationPassword, aadAuthenticationIntegrated, connectionString
      serverName: 'dfc-dev-shared-sql.database.windows.net' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated
      databaseName: 'dfc-dev-stax-editor-db' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated
      sqlUsername: 'dfc_sqladmin' # Required when authenticationType == Server
      sqlPassword: $(dfc-dev-shared-sql) # Required when authenticationType == Server
      deployType: 'sqlTask' # Options: dacpacTask, sqlTask, inlineSqlTask
      sqlFile: '$(Build.SourcesDirectory)/Sql/DropSampleTables.sql' # Required when deployType == SqlTask
      #additionalArguments: # Optional
      #sqlAdditionalArguments: # Optional
      #inlineAdditionalArguments: # Optional
      ipDetectionMethod: 'AutoDetect' # Options: autoDetect, iPAddressRange
