parameters:
  Environment: ''
  JMeterBinDir: ''
  ServerName: ''

jobs:
- deployment: TestIn_${{ parameters.Environment }}
  pool:
    name: 'NCS - jMeter'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - powershell: |
            $OutputFolderDateStamp = [DateTime]::Now.ToString("yyyy-MM-dd_HHmm")
            $(Pipeline.Workspace)/LoadTest/Invoke-Neo4jLoadTest.ps1 -JMeterBinDir ${{ parameters.JMeterBinDir }} -ServerName ${{ parameters.ServerName }} -OutputFolder /tests/$OutputFolderDateStamp
            Write-Host "##vso[task.setvariable variable=OutputFolderDateStamp]$OutputFolderDateStamp"
          displayName: 'PowerShell Script: Invoke-Neo4jLoadTest.ps1'
        - task: PublishPipelineArtifact@0
          displayName: 'Publish Artifact: LoadTestResults'
          inputs:
            targetPath: '/tests/$[variables.OutputFolderDateStamp]'
            artifactName: LoadTestResults