parameters:
  Environment: ''
  JMeterBinDir: ''
  ServerName: ''

jobs:
- deployment: TestIn_${{ parameters.Environment }}
  dependsOn: DeployTo_${{ parameters.Environment }}
  pool:
    name: 'NCS - jMeter'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          name: RunLoadTest
          displayName: 'PowerShell Script: Invoke-Neo4jLoadTest.ps1'
          inputs: 
            targetType: inline
            script: |
              $(Pipeline.Workspace)/LoadTests/Invoke-Neo4jLoadTest.ps1 -JMeterBinDir ${{ parameters.JMeterBinDir }} -ServerName ${{ parameters.ServerName }} -OutputFolder $(Build.StagingDirectory)/testresults -JmxTestFilePath $(Pipeline.Workspace)/LoadTests/NeoLoadTest.jmx
        - task: PublishPipelineArtifact@0
          displayName: 'Publish Artifact: LoadTestResults'
          inputs:
            targetPath: $(Build.StagingDirectory)/testresults
            artifactName: LoadTestResults