variables:
- name: DFCServiceTaxonomyDatabaseTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: DEV
- name: ResourceGroup
  value: dfc-dev-stax-database-rg
- name: StaxDbPublicIpAddressResourceGroup
  value: $(AksNodeResourceGroupName)
- name: neo4j-namespace
  value: neo4j
- name: neo4j-draft-namespace
  value: neo4j-draft
- name: neo4j-visit-namespace
  value: neo4j-visit