variables:
- name: DFCServiceTaxonomyDatabaseTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: PP
- name: ResourceGroup
  value: dfc-pp-stax-database-rg
- name: StaxDbPublicIpAddressResourceGroup
  value: $(AksNodeResourceGroupName)
# - name: InternalLoadBalancerAnnotation
#   value: 'service.beta.kubernetes.io/azure-load-balancer-internal: "true"'