variables:
- name: DFCServiceTaxonomyDatabaseTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: PP
- name: ResourceGroup
  value: dfc-pp-stax-database-rg
- name: StaxDbPublicIpAddressResourceGroup
  value: $(AksNodeResourceGroupName)