variables:
- name: DFCServiceTaxonomyDatabaseTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: PP
- name: ResourceGroup
  value: dfc-pp-stax-database-rg
- name: StaxDbPublicIpAddressResourceGroup
  value: $(AksNodeResourceGroupName)
- name: neo4j-namespace
  value: neo4j
- name: neo4j-draft-namespace
  value: neo4j-draft
- name: neo4j-visit-namespace
  value: neo4j-visit
- name: neo4j-1-namespace
  value: neo4j-1
- name: neo4j-draft-1-namespace
  value: neo4j-draft-1
- name: neo4j-visit-1-namespace
  value: neo4j-visit-1