variables:
- name: DFCServiceTaxonomyDatabaseTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: SIT
- name: ResourceGroup
  value: dfc-sit-stax-database-rg
- name: StaxDbPublicIpAddressResourceGroup
  value: $(AksNodeResourceGroupName)